### Numpy : Package for multi dimensional array

-> For seeing syntax of any method use shift + tab

In [3]:
import numpy as np

In [ ]:
### whenever we do indexing/slicing , i.e , when we use lists, we use square brackets "[]"

In [ ]:
### in all other cases we use parenthesis "()"

##### Creating an array using numpy

In [2]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

------------------------------------------------------------------------------------------------------------------------

##### arange() method in Numpy

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

The arange() method has a start, a stop and a step parameter. default start value is 0, default step value is 1.

------------------------------------------------------------------------------------------------------------------------

##### zeros() method in NumPy

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

zeros() method prints an array of zeroes 

-> Default return data type is float

-> We can change the return data type to integer, boolean or string

In [10]:
np.zeros(5,dtype=str)

array(['', '', '', '', ''], dtype='<U1')

In [11]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [12]:
np.zeros(5,dtype=bool)

array([False, False, False, False, False])

we can also specify if we want rows and columns both in the array

In [15]:
np.zeros((5,3),dtype=int) #### 5 rows and 3 columns

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

------------------------------------------------------------------------------------------------------------------------

##### ones() method in NumPy

-> Similar to zeros() function, used to print an array having "1"s

In [19]:
np.ones((3,4),dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [20]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#### Create an array of zeroes with 2 rows and 10 columns

In [18]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

------------------------------------------------------------------------------------------------------------------------

##### linspace() method in NumPy

-> Prints an array having linearly spaced numbers in the given interval

-> Has a start, stop and 'number of terms' parameter

-> default number of terms is 50

In [21]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [22]:
np.linspace(1,4)

array([1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
       1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
       1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
       1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
       2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
       2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
       2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
       3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
       3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
       3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ])

In [23]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

------------------------------------------------------------------------------------------------------------------------

##### eye() method in NumPy

-> returns an identity matrix

-> default return type is float

-> Syntax of eye() method has parameters for rows,columns, return datatype and for specifying the diagonal where 1s will be printed

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.eye(3,3,-1,dtype=int) #### -1 makes the 1s appear in the diagonal  below the main diagonal

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [31]:
np.eye(3,3,1) ##### positive 1 makes the 1s appear in the diagonal above the main diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

------------------------------------------------------------------------------------------------------------------------

#### Methods to print array with random values

-> random numbers can be printed using random() method of NumPy

##### random.rand() 

In [34]:
np.random.rand(3,2) #### random distribution in range (0,1) 

array([[0.27111461, 0.2355675 ],
       [0.9109638 , 0.05235742],
       [0.1729322 , 0.16280249]])

##### random.randn()

In [44]:
np.random.randn(5) ##### random distribution in range N

array([-1.17604838,  0.3013983 , -0.94229923,  3.24445425, -0.17069158])

##### random.randint()

In [47]:
np.random.randint(34,100,20) ##### (start value, end value, size value) , here 20 is the size of array to be printed

array([41, 59, 45, 51, 95, 87, 66, 51, 82, 85, 82, 62, 99, 37, 79, 34, 60,
       58, 66, 50])

In [48]:
np.random.randint(2)

1

------------------------------------------------------------------------------------------------------------------------

##### arange() method in NumPy

In [52]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

-> we get arranged data lying in the specified range

------------------------------------------------------------------------------------------------------------------------

##### reshape() method  

In [53]:
b=np.random.randint(0,100,20)

we can reshape the given data into specified amount of rows and columns.

In [62]:
b.reshape(4,5)

array([[49, 90, 65, 78, 99],
       [90, 57, 25, 43, 15],
       [35,  9, 20, 14, 47],
       [27, 26, 29, 45, 80]])

In [55]:
b

array([49, 90, 65, 78, 99, 90, 57, 25, 43, 15, 35,  9, 20, 14, 47, 27, 26,
       29, 45, 80])

however if the number of rows and columns together cannot accomodate all elements, it will give error

In [56]:
b.reshape(3,1)

ValueError: cannot reshape array of size 20 into shape (3,1)

Also error arises if the rows and columns together have more capacity than number of elements

In [57]:
b.reshape(10,10)

ValueError: cannot reshape array of size 20 into shape (10,10)

------------------------------------------------------------------------------------------------------------------------

#### NumPy methods to find extreme values of an Array 

-> min() method to find minimum value

-> max() method to find maximum value

-> argmin() and argmax() to find the indices of the minimum and maximum values respectively

In [63]:
b.argmin()

11

In [69]:
b.min()

9

In [70]:
b.max()

99

In [71]:
b.argmax()

4

In [73]:
b.dtype

dtype('int32')

------------------------------------------------------------------------------------------------------------------------

#### Transpose of an array

Transpose of an array can be made by typing name of the array followed by ".T"

In [75]:
c

array([[49, 90, 65, 78, 99],
       [90, 57, 25, 43, 15],
       [35,  9, 20, 14, 47],
       [27, 26, 29, 45, 80]])

In [77]:
c.T

array([[49, 90, 35, 27],
       [90, 57,  9, 26],
       [65, 25, 20, 29],
       [78, 43, 14, 45],
       [99, 15, 47, 80]])

------------------------------------------------------------------------------------------------------------------------

#### Indexing in an array

Arrays are also indexed , hence they can be sliced using the logics of indices

In [78]:
b

array([49, 90, 65, 78, 99, 90, 57, 25, 43, 15, 35,  9, 20, 14, 47, 27, 26,
       29, 45, 80])

In [79]:
b[1:5]

array([90, 65, 78, 99])

In [80]:
b[:5]

array([49, 90, 65, 78, 99])

In [81]:
b[6:]


array([57, 25, 43, 15, 35,  9, 20, 14, 47, 27, 26, 29, 45, 80])

In [82]:
b[3:-5]

array([78, 99, 90, 57, 25, 43, 15, 35,  9, 20, 14, 47])

In [83]:
b[-3:]

array([29, 45, 80])

In [84]:
b[::3]

array([49, 78, 57, 15, 20, 27, 45])

In [85]:
b[:5]=100
b

array([100, 100, 100, 100, 100,  90,  57,  25,  43,  15,  35,   9,  20,
        14,  47,  27,  26,  29,  45,  80])

------------------------------------------------------------------------------------------------------------------------

### Two dimensional array in Python using NumPy

In [90]:
m=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7])) #### creating an array
m

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [89]:
m[2][2] ### accessing an element in the created array

24

In [92]:
m[2,:]

array([56, 76, 24,  7])

In [93]:
m[2]


array([56, 76, 24,  7])

In [95]:
m[:,(3,2)] ### arranging all elements of 3rd and 2nd columns of each row into a new matrix

array([[23,  1],
       [33, 21],
       [ 7, 24]])

------------------------------------------------------------------------------------------------------------------------

#### unique() method in NumPy

In [ ]:
sports=np.array(['golf','cricket','football','cricket','football'])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

'U8' indicates number of characters in the longest string

### Selection techniques in NumPy

In [6]:
s=np.arange(1,20)

In [7]:
s

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
s+s

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

#### Different mathematical operations performed on all elements of the array

In [13]:
np.exp(s)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [12]:
np.sqrt(s)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [14]:
np.log(s)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [15]:
np.max(s)

19

In [16]:
np.min(s)

1

In [17]:
np.argmin(s)

0

In [18]:
np.argmax(s)

18

In [19]:
np.square(s)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [20]:
np.std(s)

5.477225575051661

In [21]:
np.mean(s)

10.0

In [22]:
np.var(s)

30.0

In [23]:
s=np.random.randn(3,4)
s
np.round(s,decimals=4)

array([[-0.242 ,  0.9855,  0.3026, -0.8457],
       [-0.5254, -0.5692, -0.2855,  0.8452],
       [-1.5086, -1.3331,  0.2899,  1.5994]])

In [27]:
np.round(s,decimals=2)

array([[-0.24,  0.99,  0.3 , -0.85],
       [-0.53, -0.57, -0.29,  0.85],
       [-1.51, -1.33,  0.29,  1.6 ]])